import {  Poppins,} from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/Components/Footer";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "NovaCart",
  description: "Generated by create NovaCart",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}
      >
        <Navbar/>
        <div className="">
          {children}
        </div>
        <Footer/>
        <Toaster />
      </body>
    </html>
  );
}